
'use strict';
(function(){
 const $=id=>document.getElementById(id),$$=q=>Array.from(document.querySelectorAll(q));
 const STORE='undertone.v1';
 const DEFAULTS={musicSource:'library',track:'broken-glimmers',music:70,autoMix:false,preset:'soft',route:'speakers',hz:10,carrier:220,beats:true,beatVolume:14,master:35,pad:74,melody:26,rain:10,ocean:0,noise:10,noiseType:'brown',score:'velvet',theme:'mono',scene:'orbit',motion:60,brightness:94,eco:false,breathing:false,keepAwake:true,blackout:false,timer:0,seed:604};
 const PRESETS={
 focus:{title:'Make room for one thing.',description:'An open soundscape for your next stretch of work.',label:'Focus',hz:40,carrier:340,beats:true,beatVolume:14,pad:76,melody:20,rain:0,ocean:0,noise:8,noiseType:'pink',score:'horizon'},
 soft:{title:'Find your easy focus.',description:'A little less noise. A little more room to think.',label:'Relaxed focus',hz:10,carrier:220,beats:true,beatVolume:14,pad:74,melody:26,rain:10,ocean:0,noise:10,noiseType:'brown',score:'velvet'},
 relax:{title:'You can let the day go.',description:'Slow chords. Soft edges. Nowhere else to be.',label:'Relax',hz:6,carrier:180,beats:true,beatVolume:12,pad:70,melody:18,rain:0,ocean:24,noise:8,noiseType:'pink',score:'nocturne'},
 ambient:{title:'Just a good place to be.',description:'A living soundtrack. No beats, no targets, no rush.',label:'Just ambient',hz:10,carrier:220,beats:false,beatVolume:14,pad:76,melody:30,rain:16,ocean:10,noise:6,noiseType:'brown',score:'velvet'}
 };
 const SCENES={tides:'Living contours',dunes:'Silk drift',orbit:'Energy orbit',rain:'Wet glass'};
 const NUMBERS={music:[0,100],hz:[1,40],carrier:[80,600],beatVolume:[0,100],master:[0,100],pad:[0,100],melody:[0,100],rain:[0,100],ocean:[0,100],noise:[0,100],motion:[0,100],brightness:[10,100],timer:[0,180],seed:[1,9999]};
 const ENUMS={musicSource:['library','generated'],track:Object.keys(UT_TRACKS),preset:Object.keys(PRESETS),route:['speakers','headphones'],noiseType:['brown','pink','white'],score:Object.keys(UT_SCORES),theme:Object.keys(UT_THEMES),scene:Object.keys(SCENES)};
 const BOOLS=['autoMix','beats','eco','breathing','keepAwake','blackout'];
 const clamp=(x,min,max)=>Math.max(min,Math.min(max,x));
 const cleanSettings=obj=>{const s={...DEFAULTS};if(!obj||typeof obj!=='object'||Array.isArray(obj))return s;if(!Object.prototype.hasOwnProperty.call(obj,'musicSource')&&Object.prototype.hasOwnProperty.call(obj,'score'))s.musicSource='generated';for(const [k,[min,max]]of Object.entries(NUMBERS)){if(typeof obj[k]==='number'&&Number.isFinite(obj[k]))s[k]=clamp(obj[k],min,max);}for(const[k,v]of Object.entries(ENUMS))if(v.includes(obj[k]))s[k]=obj[k];for(const k of BOOLS)if(typeof obj[k]==='boolean')s[k]=obj[k];s.hz=Math.round(s.hz*2)/2;s.carrier=Math.round(s.carrier);s.seed=Math.round(s.seed);return s;};
 const cleanMixes=arr=>Array.isArray(arr)?arr.slice(0,12).filter(x=>x&&typeof x.name==='string').map(x=>({id:typeof x.id==='string'?x.id.slice(0,80):String(Date.now()+Math.random()),name:x.name.slice(0,48),settings:cleanSettings(x.settings)})):[];
 const cleanHistory=arr=>Array.isArray(arr)?arr.slice(0,40).filter(x=>x&&Number.isFinite(x.seconds)&&Number.isFinite(x.date)).map(x=>({id:String(x.id||Math.random()).slice(0,80),date:clamp(x.date,0,Date.now()+86400000),seconds:clamp(x.seconds,0,86400),preset:ENUMS.preset.includes(x.preset)?x.preset:'soft',hz:clamp(Number(x.hz)||10,1,40),beats:!!x.beats,route:x.route==='headphones'?'headphones':'speakers',rating:['helped','neutral','notforme'].includes(x.rating)?x.rating:null,mixed:!!x.mixed})):[];
 let stored={};try{stored=JSON.parse(localStorage.getItem(STORE)||'{}')||{};}catch(_){}
 let state=cleanSettings(stored.settings),saved=cleanMixes(stored.saved),history=cleanHistory(stored.history),storageAvailable=true;
 if(!stored.settings&&/SmartTV|Tizen|Web0S|WebOS|HbbTV|NetCast/i.test(navigator.userAgent))state.eco=true;
 let shared=false;try{if(location.hash.startsWith('#mix=')){const raw=location.hash.slice(5);if(raw.length>20000)throw new Error('Oversized link');state=cleanSettings(JSON.parse(decodeURIComponent(raw)));shared=true;}}catch(_){setTimeout(()=>toast('That mix link could not be read. Your saved settings were kept.'),300);}
 let playing=false,busy=false,sessionStart=null,sessionSnapshot=null,sessionMixed=false,cinema=true,idleTimer=null,wakeLock=null,wakePending=false,installPrompt=null,prevFocus=null,tab='sound',muted=false,lastMaster=state.master||35,toastTimeout=null,heroTimer=null,autoEnding=false,saveTimeout=null;
 const audio=new UndertoneAudio();audio.liveSettings=state;
 let trackPlayer=null,audioReady=null,musicRequest=0,autoMixRevision=0,musicLoading=false,musicMessage='Ready to load when you press Play.';
 const effectiveAudioSettings=()=>({...state,musicSource:state.musicSource==='library'&&trackPlayer?.currentTrack?'library':'generated'});
 async function ensureAudio(){if(!audioReady)audioReady=audio.init(effectiveAudioSettings()).catch(async error=>{await audio.destroy();audioReady=null;throw error;});await audioReady;}
 function musicTitle(){return state.musicSource==='library'?(trackPlayer?.currentTrack?.title||UT_TRACKS[state.track].title):UT_SCORES[state.score].name;}
 async function prepareMusic(){
  if(state.musicSource!=='library')return;
  const target=UT_TRACKS[state.track],request=++musicRequest;
  await ensureAudio();
  if(request!==musicRequest||state.musicSource!=='library')return;
  if(!trackPlayer)trackPlayer=new UndertoneTrackPlayer(audio.ctx,audio.limiter,{onStatus:event=>{
   if(event.trackChanged&&event.currentTrack&&state.musicSource==='library'&&!event.loading){
    state.track=event.currentTrack.id;musicLoading=false;musicMessage=event.error?'Track unavailable; keeping the current music.':event.offlineAvailable?'Stereo FLAC · saved for offline listening':'Stereo FLAC · ready in this session';persist();sync();setupMedia();
   }
  }});
  trackPlayer.setAutoMix(Object.values(UT_TRACKS),state.autoMix);
  trackPlayer.setVolume(state.music);
  musicLoading=trackPlayer.currentTrack?.id!==target.id;if(musicLoading)musicMessage='Loading lossless music…';sync();
  try{
   await trackPlayer.load(target);
   if(request!==musicRequest||state.musicSource!=='library')return;
   musicLoading=false;musicMessage=trackPlayer.offlineAvailable?'Stereo FLAC · saved for offline listening':'Stereo FLAC · ready in this session; offline storage unavailable';
   audio.apply(effectiveAudioSettings());if(playing)await trackPlayer.play();sync();setupMedia();
  }catch(error){
   if(request!==musicRequest)return;
   musicLoading=false;musicMessage=error.message||'This track could not load.';
   if(trackPlayer.currentTrack){state.track=trackPlayer.currentTrack.id;persist();}
   sync();throw error;
  }
 }
 for(const track of Object.values(UT_TRACKS)){const option=document.createElement('option');option.value=track.id;option.textContent=track.title;$('track').appendChild(option);}

 function persist(){clearTimeout(saveTimeout);saveTimeout=setTimeout(()=>{try{localStorage.setItem(STORE,JSON.stringify({version:1,settings:state,saved,history}));storageAvailable=true;}catch(_){if(storageAvailable)toast('Browser storage is unavailable. Use Export backup to keep your mixes.');storageAvailable=false;}},180);}
 function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>$('toast').hidden=true,4500);}
 function announce(text){$('announcer').textContent=text;}
 function fmtHz(n){return Number.isInteger(n)?String(n):n.toFixed(1);}
 function timeFormat(seconds){const sec=Math.max(0,Math.ceil(seconds));const h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s=sec%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;}
 function icon(name){return `<svg class="icon" aria-hidden="true"><use href="#i-${name}"/></svg>`;}
 function button(text,classes=''){const b=document.createElement('button');b.type='button';b.className=classes;b.textContent=text;return b;}
 const mixLabels={pad:['Ambient chords','Slow, evolving harmony'],melody:['Soft notes','Sparse, bell-like accents'],rain:['Rain texture','A synthesized rain-like wash'],ocean:['Ocean swell','A synthesized, rolling texture'],noise:['Noise bed','An even layer underneath']};
 for(const [key,[name,desc]]of Object.entries(mixLabels)){const row=document.createElement('div');row.className='slider-row';if(key==='pad'||key==='melody')row.dataset.generated='true';row.innerHTML=`<div class="label-row"><label for="${key}">${name}</label><output id="${key}Out"></output></div><input id="${key}" data-setting="${key}" type="range" min="0" max="100"><div class="label-desc">${desc}</div>`;$('mixerSliders').appendChild(row);}
 for(const [key,theme] of Object.entries(UT_THEMES)){const b=button('', 'theme');b.dataset.theme=key;b.setAttribute('aria-pressed','false');const swatches=document.createElement('span');swatches.className='theme-swatches';swatches.setAttribute('aria-hidden','true');[theme.bg,theme.line,theme.accent].forEach(color=>{const i=document.createElement('i');i.style.background=color;swatches.appendChild(i);});b.appendChild(swatches);b.appendChild(document.createTextNode(theme.name));$('themeGrid').appendChild(b);}
 const drawings={tides:'<path d="M0 39Q30 5 70 33T170 30M0 44Q30 10 70 38T170 35M0 49Q30 15 70 43T170 40M0 54Q30 20 70 48T170 45M0 59Q30 25 70 53T170 50"/>',dunes:'<path d="M0 22C50 55 80 -6 170 28M0 27C50 60 80 -1 170 33M0 32C50 65 80 4 170 38M0 37C50 70 80 9 170 43M0 42C50 75 80 14 170 48"/>',orbit:'<ellipse cx="85" cy="34" rx="53" ry="20"/><ellipse cx="85" cy="34" rx="47" ry="16"/><ellipse cx="85" cy="34" rx="40" ry="12"/><ellipse cx="85" cy="34" rx="32" ry="8"/>',rain:'<g opacity=".25"><circle cx="30" cy="32" r="12"/><circle cx="120" cy="42" r="18"/></g><path d="M45 0v24M93 16v30M140 0v17"/><ellipse cx="45" cy="27" rx="2" ry="4"/><ellipse cx="93" cy="48" rx="3" ry="5"/><ellipse cx="140" cy="20" rx="2" ry="4"/><ellipse cx="68" cy="14" rx="2" ry="3"/>'};
 for(const[key,name]of Object.entries(SCENES)){const b=button('','scene-option');b.dataset.scene=key;b.setAttribute('aria-pressed','false');b.innerHTML=`<svg viewBox="0 0 170 66" aria-hidden="true">${drawings[key]}</svg><span>${name}</span>`;$('sceneOptions').appendChild(b);}
 const visual=new UndertoneVisuals($('visual'),()=>state,()=>state.musicSource==='library'&&trackPlayer?.playing?trackPlayer.visualLevels():audio.visualLevels());visual.reseed(state.seed);visual.reduced.addEventListener?.('change',()=>sync());
 function applyTheme(){const t=UT_THEMES[state.theme],root=document.documentElement;for(const k of ['bg','bg2','surface','raised','text','secondary','muted','line','accent','strong','ink'])root.style.setProperty('--'+k,t[k]);document.querySelector('meta[name=theme-color]').content=t.bg;visual.dirty=true;}
 function sync(){const p=PRESETS[state.preset];$('intentionTitle').textContent=p.title;$('intentionDescription').textContent=p.description;$$('[data-preset]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.preset===state.preset)));$$('[data-route]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.route===state.route)));$$('[data-theme]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.theme===state.theme)));$$('[data-scene]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.scene===state.scene)));$$('[data-timer]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.timer===state.timer)));$$('[data-hz]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.hz===state.hz)));
  $('heroFrequency').textContent=state.beats?fmtHz(state.hz):'Just be.';$('heroUnit').hidden=!state.beats;$('heroNote').textContent=state.beats?(state.route==='headphones'?'Stereo binaural · headphones required':'Gentle speaker pulse · not binaural'):'Ambient music · no beat layer';$('stageState').textContent=state.preset==='ambient'?'No targets. No rush.':`A space for ${p.label.toLowerCase()}`;
  $('hzValue').textContent=fmtHz(state.hz);$('beatHz').value=state.hz;$('exactHz').value=state.hz;$('carrier').value=state.carrier;$('beatsEnabled').checked=state.beats;
  $('channelsReadout').innerHTML=state.route==='headphones'?`L ${fmtHz(state.carrier-state.hz/2)} Hz<br>R ${fmtHz(state.carrier+state.hz/2)} Hz`:`Pulse: ${fmtHz(state.hz)} cycles / sec<br>Tone: ${state.carrier} Hz`;
  $('routeLabel').textContent=state.route==='headphones'?'Headphones':'TV / speakers';$('routeIcon').setAttribute('href',state.route==='headphones'?'#i-headphones':'#i-screen');$('headphoneChecks').hidden=state.route!=='headphones';$('routeNote').innerHTML=state.route==='speakers'?'Speaker mode gently varies a tone’s loudness. It is <strong>not binaural</strong>, and binaural study results do not automatically apply to it.':'Each ear gets a separate tone. Their difference is the binaural beat. Headphones must preserve <strong>left / right separation</strong>.';
  $('frequencyEvidence').textContent=state.hz>=30?'40 Hz has mixed attention-study results. Treat this range as experimental—not a guaranteed focus boost.':state.hz>=13?'Beta-range beats have mixed findings. 16 Hz is an optional experiment, not a validated focus setting.':state.hz>=8?'10 Hz is an exploratory relaxed-focus starting point, not a proven optimum.':'Theta-range beats have preliminary, mixed findings. 6 Hz is an exploratory relaxation setting, not a treatment.';
  if(!state.beats)$('frequencyEvidence').textContent='Beat layer is off. Music and texture levels remain independent.';
  for(const el of $$('[data-setting]')){const key=el.dataset.setting;el.value=state[key];el.setAttribute('aria-valuetext',state[key]+' percent');if($(key+'Out'))$(key+'Out').textContent=state[key]+'%';}
  for(const id of ['masterVolume','masterPanel']){$(id).value=state.master;$(id).setAttribute('aria-valuetext',state.master+' percent');}$('masterPanelOut').textContent=state.master+'%';$('volumeIcon').setAttribute('href',state.master===0?'#i-mute':'#i-volume');$('muteButton').setAttribute('aria-label',state.master===0?'Unmute audio':'Mute audio');
  ['score','noiseType','musicSource','track'].forEach(k=>$(k).value=state[k]);
  const recorded=state.musicSource==='library',track=UT_TRACKS[state.track];
  $('trackLabel').hidden=!recorded;$('trackDetails').hidden=!recorded;$('musicVolumeRow').hidden=!recorded;$('autoMixRow').hidden=!recorded;$('autoMix').checked=state.autoMix;$('nextTrack').disabled=musicLoading;$('score').hidden=recorded;$('scoreLabel').hidden=recorded;
  $$('[data-generated]').forEach(row=>row.hidden=recorded);
  $('trackDescription').textContent=track.description;$('musicStatus').textContent=musicMessage;
  $('trackCredit').replaceChildren(document.createTextNode(track.title+' by '+track.artist+' · '));
  const source=document.createElement('a');source.href=track.sourceUrl;source.target='_blank';source.rel='noopener noreferrer';source.textContent='Source';
  const license=document.createElement('a');license.href=track.licenseUrl;license.target='_blank';license.rel='noopener noreferrer';license.textContent=track.license;
  $('trackCredit').append(source,document.createTextNode(' · '),license,document.createTextNode(track.loop==='crossfade'?' · '+track.crossfadeSeconds+'-second overlap at repeat':' · Artist-supplied loop'));
  ['eco','breathing','keepAwake','blackout'].forEach(k=>$(k).checked=state[k]);$('sceneName').textContent=SCENES[state.scene];$('visual').setAttribute('aria-label',SCENES[state.scene]+'. '+(state.motion===0||visual.reduced.matches?'Still composition.':'Slowly evolving scene. Motion can be disabled in Scene controls.'));$('seedLabel').textContent=String(state.seed).padStart(4,'0');$('nowTitle').textContent=musicTitle();$('sceneCaption').textContent=state.blackout?'Audio stays. The screen can rest.':state.scene==='rain'?'A window onto nowhere in particular.':'Made here, in the moment. Nothing to queue.';
  document.body.classList.toggle('blackout',state.blackout);$('breathOverlay').hidden=!state.breathing||!playing;$('stageCenter').style.visibility=state.breathing&&playing?'hidden':'';
  if(visual.reduced.matches)$('motionNote').textContent='Your system’s reduced-motion setting is on. The scene remains still.';else $('motionNote').textContent=state.motion===0?'Still image. Sound keeps playing.':'Slow by design. Set to zero for a still image.';
  updatePlayback();updateTimer();applyTheme();
 }
 function change(patch,notice){const previous={...state};state=cleanSettings({...state,...patch});if(previous.autoMix!==state.autoMix)autoMixRevision++;audio.liveSettings=effectiveAudioSettings();if(audio.ready)audio.apply(effectiveAudioSettings());trackPlayer?.setVolume(state.music);if(previous.autoMix!==state.autoMix||previous.musicSource!==state.musicSource)trackPlayer?.setAutoMix(Object.values(UT_TRACKS),state.autoMix&&state.musicSource==='library');let musicWork=Promise.resolve();
  if(previous.musicSource!==state.musicSource||previous.track!==state.track){
   musicRequest++;
   if(state.musicSource==='generated'){musicLoading=false;trackPlayer?.stop(.7);musicMessage='Generated music selected.';}
   else if(audio.ready){musicWork=prepareMusic();musicWork.catch(e=>toast(e.message+' Choose another track or Generated music.'));}
   else musicMessage='Ready to load when you press Play.';
  }if(sessionStart!==null&&Object.keys(patch).some(k=>!['theme','scene','seed','motion','brightness','eco','keepAwake','blackout','breathing','timer'].includes(k)))sessionMixed=true;if(previous.seed!==state.seed)visual.reseed(state.seed);if(previous.keepAwake!==state.keepAwake){if(state.keepAwake&&playing)acquireWake();else releaseWake();}sync();persist();if(notice)toast(notice);return musicWork;}
 function setPreset(key){const p=PRESETS[key],patch={preset:key};for(const k of ['hz','carrier','beats','beatVolume','pad','melody','rain','ocean','noise','noiseType','score'])patch[k]=p[k];change(patch);announce(`${p.label}. ${p.beats?p.hz+' hertz, '+(state.route==='headphones'?'binaural':'speaker pulse'):'Beat layer off'}.`);revealHero();}
 function updatePlayback(){document.body.classList.toggle('playing',playing);$('playIcon').setAttribute('href',playing?'#i-pause':'#i-play');$('playButton').setAttribute('aria-label',playing?'Pause listening':sessionStart!==null?'Resume listening':'Start listening');$('playButton').title=playing?'Pause (Space)':'Play (Space)';$('stagePlay').hidden=playing;$('stagePlay').innerHTML=icon('play')+(sessionStart!==null?'Resume listening':'Start listening');$('nowSub').textContent=musicLoading?'Loading lossless music…':playing?(state.beats?`${fmtHz(state.hz)} Hz · ${state.route==='headphones'?'Binaural':'Speaker pulse'}`:'Ambient only · beat layer off'):sessionStart!==null?'Paused. Your space is still here.':'Ready when you are';if(navigator.mediaSession)try{navigator.mediaSession.playbackState=playing?'playing':'paused';}catch(_){}$('breathOverlay').hidden=!state.breathing||!playing;$('stageCenter').style.visibility=state.breathing&&playing?'hidden':'';}
 async function togglePlay(){if(busy||audio.testBusy)return;busy=true;$('playButton').disabled=true;try{if(playing){await audio.pause();trackPlayer?.pause();playing=false;releaseWake();revealHero();}else{await ensureAudio();await prepareMusic();await audio.play(effectiveAudioSettings());if(state.musicSource==='library')await trackPlayer?.play();playing=true;if(sessionStart===null){sessionStart=audio.ctx.currentTime;sessionSnapshot={...state};sessionMixed=false;audio.armTimer(state.timer?state.timer*60:0);}acquireWake();revealHero();setupMedia();}updatePlayback();resetIdle();}catch(e){playing=false;toast(e.message||'Audio could not start. Tap Play again, or open this page in your browser.');console.error(e);}finally{busy=false;$('playButton').disabled=false;}}
 function updateTimer(){const remain=audio.ctx&&sessionStart!==null?audio.remaining():null;$('timerReadout').textContent=remain!==null?timeFormat(remain):state.timer?state.timer+' min':'No timer';$('timerButton').setAttribute('aria-label',remain!==null?`${timeFormat(remain)} remaining. Change session timer.`:'Set session timer');const progress=remain!==null&&state.timer>0?clamp(1-remain/(state.timer*60),0,1)*100:0;$('sessionProgress').style.width=progress+'%';}
 async function finishSession(auto=false){if(busy||autoEnding)return;autoEnding=true;busy=true;try{if(sessionStart!==null&&audio.ctx){const elapsed=Math.max(0,audio.ctx.currentTime-sessionStart);if(elapsed>=20){const s=sessionSnapshot||state;history.unshift({id:String(Date.now()),date:Date.now(),seconds:Math.round(elapsed),preset:s.preset,hz:s.hz,beats:s.beats,route:s.route,rating:null,mixed:sessionMixed});history=history.slice(0,40);}}await audio.stop();trackPlayer?.stop();playing=false;sessionStart=null;sessionSnapshot=null;releaseWake();persist();renderHistory();updatePlayback();updateTimer();revealHero();wakeUI();if(auto)toast('Session complete. Take a moment before the next thing.');else toast('Session ended. Your mix is ready for next time.');}catch(e){toast('Could not stop normally. Reload the page to stop all audio.');console.error(e);}finally{autoEnding=false;busy=false;}}
 function setTimer(minutes){change({timer:minutes});if(sessionStart!==null&&audio.ctx)audio.armTimer(minutes*60);updateTimer();announce(minutes?`${minutes}-minute timer. Audio fades out at the end.`:'Timer off.');}
 function revealHero(){clearTimeout(heroTimer);$('stageCenter').classList.remove('is-faded');if(playing&&!cinema)heroTimer=setTimeout(()=>$('stageCenter').classList.add('is-faded'),13000);}
 async function acquireWake(){if(!state.keepAwake||!playing||document.hidden||wakeLock||wakePending)return;if(!('wakeLock'in navigator)){$('wakeDescription').textContent='Not supported by this browser. Adjust your device’s sleep settings.';return;}wakePending=true;try{wakeLock=await navigator.wakeLock.request('screen');$('wakeDescription').textContent='Screen-awake request is active.';wakeLock.addEventListener('release',()=>{wakeLock=null;$('wakeDescription').textContent='Released by the browser; will retry when you return.';});if(!playing||!state.keepAwake)await releaseWake();}catch(_){$('wakeDescription').textContent='The browser declined. Power-saving or device settings may override this.';}finally{wakePending=false;}}
 async function releaseWake(){if(wakeLock)try{await wakeLock.release();}catch(_){}wakeLock=null;}
 function setupMedia(){if(!('mediaSession'in navigator))return;try{if('MediaMetadata'in window)navigator.mediaSession.metadata=new MediaMetadata({title:musicTitle(),artist:'Undertone',album:PRESETS[state.preset].label});navigator.mediaSession.setActionHandler('play',()=>{if(!playing)togglePlay();});navigator.mediaSession.setActionHandler('pause',()=>{if(playing)togglePlay();});navigator.mediaSession.setActionHandler('stop',()=>finishSession());}catch(_){} }
 let panelCloseTimer=null,tabMotionRevision=0,tabAnimations=[];
 const calmEase='cubic-bezier(.22,1,.36,1)',motionReduced=()=>visual.reduced?.matches;
 function cancelTabAnimations(){for(const animation of tabAnimations)try{animation.cancel();}catch(_){}tabAnimations=[];}
 function setTabState(name,focus=false){tab=name;$$('[data-tab]').forEach(b=>{const selected=b.dataset.tab===name;b.setAttribute('aria-selected',String(selected));b.tabIndex=selected?0:-1;});$$('[role=tabpanel]').forEach(p=>p.hidden=p.id!=='pane-'+name);$('panelScroll').scrollTop=0;if(name==='sessions'){renderSaved();renderHistory();}if(focus)$('tab-'+name).focus();}
 async function activateTab(name,focus=false,animate=true){const target=$('pane-'+name),current=$$('[role=tabpanel]').find(p=>!p.hidden);if(!target||current===target||!animate||motionReduced()||typeof target.animate!=='function'){cancelTabAnimations();setTabState(name,focus);return;}const revision=++tabMotionRevision;cancelTabAnimations();$$('[data-tab]').forEach(b=>{const selected=b.dataset.tab===name;b.setAttribute('aria-selected',String(selected));b.tabIndex=selected?0:-1;});if(focus)$('tab-'+name).focus();const out=current.animate([{opacity:1,transform:'translateY(0)'},{opacity:0,transform:'translateY(-6px)'}],{duration:130,easing:'ease-out',fill:'both'});tabAnimations=[out];try{await out.finished;}catch(_){}if(revision!==tabMotionRevision)return;out.cancel();current.hidden=true;target.hidden=false;$('panelScroll').scrollTop=0;if(name==='sessions'){renderSaved();renderHistory();}tab=name;const incoming=target.animate([{opacity:0,transform:'translateY(8px)'},{opacity:1,transform:'translateY(0)'}],{duration:220,easing:calmEase,fill:'both'});tabAnimations=[incoming];try{await incoming.finished;}catch(_){}if(revision===tabMotionRevision){incoming.cancel();tabAnimations=[];}}
 function finishPanelClose(){const scrim=$('scrim');scrim.hidden=true;scrim.classList.remove('is-closing');document.body.classList.remove('panel-open');$('shell').removeAttribute('inert');$('shell').removeAttribute('aria-hidden');if(prevFocus&&prevFocus.getClientRects().length)prevFocus.focus();else $('openSettings').focus();resetIdle();}
 function openPanel(name='sound'){clearTimeout(panelCloseTimer);tabMotionRevision++;cancelTabAnimations();prevFocus=document.activeElement;wakeUI();const scrim=$('scrim');scrim.hidden=false;scrim.classList.remove('is-closing');document.body.classList.add('panel-open');$('shell').setAttribute('inert','');$('shell').setAttribute('aria-hidden','true');setTabState(name);requestAnimationFrame(()=>requestAnimationFrame(()=>scrim.classList.add('is-open')));$('closePanel').focus();}
 function closePanel(){const scrim=$('scrim');if(scrim.hidden)return;clearTimeout(panelCloseTimer);tabMotionRevision++;cancelTabAnimations();scrim.classList.remove('is-open');scrim.classList.add('is-closing');if(motionReduced())finishPanelClose();else panelCloseTimer=setTimeout(finishPanelClose,360);}
 function resetIdle(){clearTimeout(idleTimer);if(cinema&&playing&&$('scrim').hidden){idleTimer=setTimeout(()=>{if(!playing||!$('scrim').hidden)return;document.body.classList.add('idle');if(document.activeElement&&document.activeElement!==document.body)document.activeElement.blur();},6500);}}
 function wakeUI(){document.body.classList.remove('idle');resetIdle();}
 function setCinema(value,{silent=false}={}){cinema=value;document.body.classList.toggle('cinema',value);document.body.classList.remove('idle');$('cinemaExit').hidden=true;$('sceneSettings').hidden=false;$('tvButton').setAttribute('aria-pressed',String(value));$('enterTv').textContent=value?'Use standard layout':'Enter immersive layout';setTimeout(()=>{visual.resize();$('playButton').focus();},60);resetIdle();if(value&&!silent)toast('Immersive view. Controls tuck away while playing; Tune opens the full control panel.');else if(!value)clearTimeout(idleTimer);}
 async function fullscreen(){try{if(document.fullscreenElement){await document.exitFullscreen();return;}const fn=document.documentElement.requestFullscreen||document.documentElement.webkitRequestFullscreen;if(fn)await fn.call(document.documentElement);else toast('Full screen is not available here. TV mode still gives you an uncluttered view.');}catch(_){toast('This browser blocked full screen. TV mode still works.');}}
 let reseedBusy=false;
 async function randomView(){if(reseedBusy)return;const nextSeed=Math.floor(Math.random()*9999)+1,stage=$('stage');if(motionReduced()){change({seed:nextSeed});return;}reseedBusy=true;$('newScene').disabled=true;$('reseedPanel').disabled=true;stage.classList.add('is-reseeding');await new Promise(resolve=>setTimeout(resolve,300));change({seed:nextSeed});await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));stage.classList.remove('is-reseeding');await new Promise(resolve=>setTimeout(resolve,460));$('newScene').disabled=false;$('reseedPanel').disabled=false;reseedBusy=false;}
 function renderSaved(){const root=$('savedMixes');root.replaceChildren();if(!saved.length){const p=document.createElement('p');p.className='empty-copy';p.textContent='Your favorite spaces will live here.';root.appendChild(p);return;}for(const mix of saved){const row=document.createElement('div');row.className='saved-mix';const load=button('','load');const title=document.createElement('span');title.textContent=mix.name;const meta=document.createElement('small');const s=mix.settings;meta.textContent=`${UT_THEMES[s.theme].name} · ${s.beats?fmtHz(s.hz)+' Hz':'No beats'} · ${s.route==='headphones'?'Headphones':'Speakers'}`;load.append(title,meta);load.onclick=()=>{const wasTimer=state.timer;const settings={...mix.settings,master:state.master,route:state.route,keepAwake:state.keepAwake};change(settings,`Loaded “${mix.name}”. Volume and playback device kept.`);if(wasTimer!==state.timer&&sessionStart!==null)audio.armTimer(state.timer*60);revealHero();};const del=button('','ghost icon-only');del.innerHTML=icon('trash');del.setAttribute('aria-label','Delete saved mix '+mix.name);del.onclick=()=>{saved=saved.filter(x=>x.id!==mix.id);persist();renderSaved();toast('Mix removed.');};row.append(load,del);root.appendChild(row);}}
 function saveMix(){const name=$('mixName').value.trim()||`${PRESETS[state.preset].label} · ${UT_THEMES[state.theme].name}`;if(saved.length>=12){toast('You have 12 saved mixes. Remove one before saving another.');return;}saved.unshift({id:String(Date.now()),name:name.slice(0,48),settings:{...state}});$('mixName').value='';persist();renderSaved();toast('Mix saved on this device.');}
 function renderHistory(){const root=$('sessionHistory');root.replaceChildren();if(!history.length){const p=document.createElement('p');p.className='empty-copy';p.textContent='Finish a session of at least 20 seconds to add it here.';root.appendChild(p);return;}for(const item of history.slice(0,8)){const row=document.createElement('div');row.className='history-item';const title=document.createElement('div');title.className='history-title';const name=document.createElement('span');name.textContent=`${PRESETS[item.preset].label} · ${Math.max(1,Math.round(item.seconds/60))} min`;const date=document.createElement('small');date.textContent=new Date(item.date).toLocaleDateString(undefined,{month:'short',day:'numeric'});title.append(name,date);const meta=document.createElement('small');meta.textContent=`${item.beats?fmtHz(item.hz)+' Hz':'Ambient only'} · ${item.route==='headphones'?'Headphones':'Speakers'}${item.mixed?' · Settings changed':''}`;row.append(title,meta);const ratings=document.createElement('div');ratings.className='history-rating';for(const[value,label]of [['helped','Helped me'],['neutral','Neutral'],['notforme','Not for me']]){const b=button(label,'choice');b.setAttribute('aria-pressed',String(item.rating===value));b.setAttribute('aria-label',label+' for '+name.textContent+' on '+date.textContent);b.onclick=()=>{item.rating=item.rating===value?null:value;persist();renderHistory();};ratings.appendChild(b);}row.appendChild(ratings);root.appendChild(row);}}
 function downloadable(filename,data,type){const blob=new Blob([data],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function shareMix(){if(!/^https?:$/.test(location.protocol)){toast('Sharing needs a hosted URL. Export a backup while using the local preview.');return;}const url=location.origin+location.pathname+'#mix='+encodeURIComponent(JSON.stringify(state));if(navigator.share)try{await navigator.share({title:'My Undertone mix',url});return;}catch(e){if(e.name==='AbortError')return;}try{await navigator.clipboard.writeText(url);toast('Mix link copied. Open it on your other device.');}catch(_){$('shareFallback').hidden=false;$('shareUrl').value=url;$('shareUrl').focus();$('shareUrl').select();}}
 async function importBackup(file){if(!file)return;if(file.size>250000){toast('That backup is too large. Choose an Undertone JSON export.');return;}try{const data=JSON.parse(await file.text());if(data.version!==1||!data.settings||!Array.isArray(data.saved)||!Array.isArray(data.history))throw new Error('Invalid backup');const incoming=cleanMixes(data.saved);for(const mix of incoming)if(!saved.some(x=>x.id===mix.id))saved.push(mix);saved=saved.slice(0,12);for(const item of cleanHistory(data.history))if(!history.some(x=>x.id===item.id))history.push(item);history.sort((a,b)=>b.date-a.date);history=history.slice(0,40);const incomingState=cleanSettings(data.settings);change({...incomingState,master:state.master,route:state.route});if(sessionStart!==null)audio.armTimer(state.timer*60);renderSaved();renderHistory();toast('Backup imported. Existing mixes kept; device and volume unchanged.');}catch(_){toast('That file is not a valid Undertone backup. Nothing was imported.');}$('importFile').value='';}
 async function install(){if(window.matchMedia('(display-mode: standalone)').matches||navigator.standalone){toast('Undertone is already running as an installed app.');return;}if(installPrompt){await installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;return;}openPanel('about');if(window.UNDERTONE_PREVIEW||!window.isSecureContext||location.protocol==='file:')toast('Install the full PWA from HTTPS hosting. A downloaded HTML preview cannot install itself.');else if(/iPad|iPhone|iPod/.test(navigator.userAgent))toast('In Safari: Share → Add to Home Screen → Add.');else toast('Use your browser’s Install app / Add to Home Screen menu. Availability varies by browser.');}
 // Pointer and standard keyboard bindings; no hovering is required to expose actions.
 $('playButton').onclick=togglePlay;$('stagePlay').onclick=togglePlay;$('openSettings').onclick=()=>openPanel('sound');$('mixButton').onclick=()=>openPanel('sound');$('routeQuick').onclick=()=>openPanel('sound');$('saveQuick').onclick=()=>openPanel('sessions');$('timerButton').onclick=()=>openPanel('sessions');$('scienceButton').onclick=()=>openPanel('about');$('sceneSettings').onclick=()=>openPanel('scene');$('mobileTune').onclick=()=>openPanel('scene');$('closePanel').onclick=closePanel;$('scrim').addEventListener('click',e=>{if(e.target===$('scrim'))closePanel();});
 $$('[data-tab]').forEach(b=>b.onclick=()=>activateTab(b.dataset.tab,true,true));$$('[data-preset]').forEach(b=>b.onclick=()=>setPreset(b.dataset.preset));$$('[data-route]').forEach(b=>b.onclick=()=>change({route:b.dataset.route}));$$('[data-theme]').forEach(b=>b.onclick=()=>change({theme:b.dataset.theme}));$$('[data-scene]').forEach(b=>b.onclick=()=>change({scene:b.dataset.scene}));$$('[data-hz]').forEach(b=>b.onclick=()=>change({hz:+b.dataset.hz,beats:true}));$$('[data-timer]').forEach(b=>b.onclick=()=>setTimer(+b.dataset.timer));
 $$('[data-setting]').forEach(el=>el.oninput=()=>change({[el.dataset.setting]:+el.value}));$('beatsEnabled').onchange=()=>change({beats:$('beatsEnabled').checked});$('beatHz').oninput=()=>change({hz:+$('beatHz').value});$('exactHz').onchange=()=>change({hz:parseFloat($('exactHz').value)||state.hz});$('carrier').onchange=()=>change({carrier:parseFloat($('carrier').value)||state.carrier});
 for(const id of ['masterVolume','masterPanel'])$(id).oninput=()=>{muted=false;change({master:+$(id).value});};$('muteButton').onclick=()=>{if(state.master>0){lastMaster=state.master;muted=true;change({master:0});}else{muted=false;change({master:lastMaster||35});}};
 ['score','noiseType','musicSource','track'].forEach(k=>$(k).onchange=()=>change({[k]:$(k).value}));['autoMix','eco','breathing','keepAwake','blackout'].forEach(k=>$(k).onchange=()=>change({[k]:$(k).checked}));$('resetMix').onclick=()=>setPreset(state.preset);$('nextTrack').onclick=()=>{const ids=Object.keys(UT_TRACKS);change({track:ids[(ids.indexOf(state.track)+1)%ids.length]});};
 for(const side of ['Left','Right'])$('test'+side).onclick=async()=>{if(busy||audio.testBusy)return;busy=true;try{await ensureAudio();audio.liveSettings=effectiveAudioSettings();toast(side+' ear test · a quiet tone for less than one second');await audio.testChannel(side.toLowerCase());}catch(e){toast(e.message||'The channel test could not start.');}finally{busy=false;}};
 $('newScene').onclick=randomView;$('reseedPanel').onclick=randomView;$('tvButton').onclick=()=>setCinema(!cinema);$('cinemaExit').onclick=()=>setCinema(false);$('enterTv').onclick=()=>{const next=!cinema;closePanel();setCinema(next);};$('fullscreenButton').onclick=()=>{closePanel();if(!cinema)setCinema(true);fullscreen();};$('endSession').onclick=()=>finishSession(false);$('saveMix').onclick=saveMix;$('mixName').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();saveMix();}};$('shareMix').onclick=shareMix;$('exportSettings').onclick=()=>downloadable('undertone-backup.json',JSON.stringify({version:1,settings:state,saved,history},null,2),'application/json');$('importSettings').onclick=()=>$('importFile').click();$('importFile').onchange=()=>importBackup($('importFile').files[0]);$('installApp').onclick=install;
 window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('installDescription').textContent='Install Undertone for a dedicated app window and quick access. Your mixes stay on this device.';});window.addEventListener('appinstalled',()=>toast('Undertone installed.'));
 ['pointerdown','pointermove','touchstart'].forEach(ev=>window.addEventListener(ev,()=>{if(cinema)wakeUI();},{passive:true}));
 const focusables=root=>Array.from(root.querySelectorAll('button:not([disabled]),a[href],input:not([type=hidden]):not([disabled]),select:not([disabled]),summary,[tabindex="0"]')).filter(el=>el.getClientRects().length&&getComputedStyle(el).visibility!=='hidden'&&!el.closest('[hidden]')&&!el.closest('[inert]'));
 function spatialMove(direction){const root=$('scrim').hidden?$('shell'):$('panel'),els=focusables(root),current=document.activeElement;if(!els.length)return;if(!els.includes(current)){(cinema?$('playButton'):els[0]).focus();return;}const r=current.getBoundingClientRect(),cx=r.x+r.width/2,cy=r.y+r.height/2;let best=null,score=Infinity;for(const el of els){if(el===current)continue;const b=el.getBoundingClientRect(),dx=b.x+b.width/2-cx,dy=b.y+b.height/2-cy;const primary=direction==='ArrowRight'?dx:direction==='ArrowLeft'?-dx:direction==='ArrowDown'?dy:-dy;const secondary=direction==='ArrowRight'||direction==='ArrowLeft'?Math.abs(dy):Math.abs(dx);if(primary<3)continue;const overlap=direction==='ArrowRight'||direction==='ArrowLeft'?b.bottom>r.top&&b.top<r.bottom:b.right>r.left&&b.left<r.right;const value=primary+secondary*3+(overlap?0:150);if(value<score){score=value;best=el;}}if(best){best.focus();best.scrollIntoView({block:'nearest',inline:'nearest'});}}
 document.addEventListener('keydown',e=>{let key=e.key;if(e.keyCode===10009||e.keyCode===461)key='Escape';if(e.keyCode===10252||key==='MediaPlayPause'){e.preventDefault();togglePlay();return;}if(e.keyCode===415||key==='MediaPlay'){e.preventDefault();if(!playing)togglePlay();return;}if(e.keyCode===19||key==='MediaPause'){e.preventDefault();if(playing)togglePlay();return;}if(key==='Escape'){if(!$('scrim').hidden){e.preventDefault();closePanel();}else if(cinema){e.preventDefault();setCinema(false);}return;}
  if(cinema&&document.body.classList.contains('idle')){wakeUI();if(!$('scrim').hidden)return;e.preventDefault();$('playButton').focus();return;}if(cinema)resetIdle();const target=e.target,typing=target.tagName==='TEXTAREA'||target.tagName==='INPUT'&&target.type!=='range'&&target.type!=='checkbox'||target.isContentEditable;
  if(key==='Tab'&&!$('scrim').hidden){const els=focusables($('panel'));if(e.shiftKey&&target===els[0]){e.preventDefault();els[els.length-1].focus();}else if(!e.shiftKey&&target===els[els.length-1]){e.preventDefault();els[0].focus();}return;}
  if(typing||target.tagName==='SELECT')return;
  if(target.getAttribute('role')==='tab'&&['ArrowLeft','ArrowRight'].includes(key)){e.preventDefault();const tabs=$$$('[data-tab]'),i=tabs.indexOf(target),next=(i+(key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;activateTab(tabs[next].dataset.tab,true,true);return;}
  if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(key)){if(target.matches('input[type=range]')&&['ArrowLeft','ArrowRight'].includes(key))return;e.preventDefault();spatialMove(key);return;}
  if(key===' '&&(target===document.body||target===$('visual')||target===$('playButton'))){e.preventDefault();togglePlay();return;}if(key.toLowerCase()==='f'){e.preventDefault();if(!$('scrim').hidden)closePanel();setCinema(!cinema);}if(key.toLowerCase()==='m'){e.preventDefault();$('muteButton').click();}
 });
 document.addEventListener('visibilitychange',async()=>{visual.dirty=true;if(!document.hidden){if(playing&&audio.ctx&&audio.ctx.state!=='running'){try{await audio.ctx.resume();}catch(_){}if(audio.ctx.state!=='running'){playing=false;audio.running=false;updatePlayback();revealHero();toast('Your browser paused audio. Tap Play to resume.');}}if(playing)acquireWake();}});
 setInterval(()=>{updateTimer();if(playing&&audio.remaining()!==null&&audio.remaining()<=0&&!autoEnding)finishSession(true);if(playing&&state.breathing&&audio.ctx){const phase=audio.ctx.currentTime%10,inhale=phase<5;const progress=inhale?phase/5:(10-phase)/5;$('breathRing').style.setProperty('--breath',.8+progress*.3);$('breathLabel').textContent=inhale?'Breathe in, gently':'Breathe out, slowly';}},250);
 function updateConnection(){if(!navigator.onLine)$('connectionStatus').textContent='Offline · your quiet stays here';else $('connectionStatus').textContent='Music & sound, on your device';}window.addEventListener('online',updateConnection);window.addEventListener('offline',updateConnection);
 async function initPWA(){if(window.UNDERTONE_PREVIEW||location.protocol==='file:'||!window.isSecureContext||!('serviceWorker'in navigator)){$('offlineStatus').textContent='Preview mode. Audio and scenes work here. For installation and offline reloads, host the full PWA folder over HTTPS.';return;}try{const registration=await navigator.serviceWorker.register('./sw.js',{scope:'./'});await navigator.serviceWorker.ready;$('offlineStatus').textContent='Offline app cache is ready. Built-in scenes and generated audio need no connection. Music tracks are available offline after their first successful load.';if(registration.waiting)$('offlineStatus').textContent+=' Close other Undertone tabs and reopen to apply the newest version.';}catch(_){$('offlineStatus').textContent='Offline setup was not available. The app still works online; check that sw.js and the manifest are deployed beside index.html.';}}
 window.addEventListener('pagehide',()=>{try{localStorage.setItem(STORE,JSON.stringify({version:1,settings:state,saved,history}));}catch(_){}releaseWake();});
 // Browser-agent controls reuse the same state transitions as the human UI.
 const toolApi={
  getState:()=>({settings:{...state},playing,loading:musicLoading,currentTrack:trackPlayer?.currentTrack?.id||null,motionStatus:visual.reduced.matches?'system-reduced-motion':state.motion===0?'still':'animated'}),
  getOptions:()=>({scenes:SCENES,themes:Object.fromEntries(Object.entries(UT_THEMES).map(([id,t])=>[id,t.name])),presets:Object.fromEntries(Object.entries(PRESETS).map(([id,p])=>[id,p.label])),tracks:Object.fromEntries(Object.entries(UT_TRACKS).map(([id,t])=>[id,t.title]))}),
  change,setPreset,
  applyMusic:async(patch,signal)=>{
   if(signal?.aborted)throw new DOMException('Music selection canceled.','AbortError');
   if(busy)throw new Error('Playback is changing. Try again when the player is ready.');
   const previous={musicSource:state.musicSource,track:state.track,autoMix:state.autoMix};
   const work=change(patch),request=musicRequest,mixRevision=autoMixRevision;
   const cancel=()=>{if(request!==musicRequest)return;musicRequest++;trackPlayer?.cancelLoad();musicLoading=false;
    state.musicSource=previous.musicSource;state.track=trackPlayer?.currentTrack?.id||previous.track;if(autoMixRevision===mixRevision)state.autoMix=previous.autoMix;
    trackPlayer?.setAutoMix(Object.values(UT_TRACKS),state.autoMix&&state.musicSource==='library');
    if(audio.ready)audio.apply(effectiveAudioSettings());musicMessage='Music selection canceled.';sync();persist();};
   signal?.addEventListener('abort',cancel,{once:true});
   try{await work;if(signal?.aborted)throw new DOMException('Music selection canceled.','AbortError');if(request!==musicRequest)throw new Error('Music selection was superseded. Read current state before retrying.');}
   finally{signal?.removeEventListener('abort',cancel);}
  }
 };
 let removeTools=()=>{};
 function registerTools(){try{removeTools();removeTools=registerUndertoneTools(toolApi);}catch(error){removeTools=()=>{};console.warn('Undertone browser tools unavailable:',error);}}
 registerTools();window.addEventListener('pagehide',()=>removeTools());window.addEventListener('pageshow',event=>{if(event.persisted)registerTools();});
 // Local QA diagnostics. Settings and history remain on this device; there is no remote transport.
 Object.defineProperty(window,'undertoneDebug',{value:{get state(){return{...state};},get audio(){return audio;},get tracks(){return trackPlayer;},get playing(){return playing;},get savedCount(){return saved.length;},get history(){return history.map(x=>({...x}));},get cinema(){return cinema;}},writable:false});
 setCinema(true,{silent:true});sync();renderSaved();renderHistory();updateConnection();initPWA();if(!('wakeLock'in navigator))$('wakeDescription').textContent='Not supported by this browser; device sleep settings take priority.';if(shared)setTimeout(()=>toast('Shared mix loaded. Check volume and choose speakers or headphones before playing.'),450);
})();
